package serve

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"
)

// THE WIRE HAS A TYPE, AND THE TYPE IS GENERATED BY A GO TEST — NOT A NODE
// SCRIPT.
//
// `pending.suggestions` was renamed to `pending.instructions` when the agent
// stopped proposing and started editing the file. `web/typing.mjs` and
// `web/loop.mjs` both read the old field, both died with `TypeError: Cannot
// read properties of undefined`, and NOBODY NOTICED FOR WEEKS — because
// neither gate ran anywhere but on a human's laptop. That is the most
// expensive browser defect of the month and the whole of its cause is that one
// side of a contract changed and the other side was never told.
//
// So the check lives HERE, in `go test`, which is what `just verify` is made
// of: Go-only, always run, in CI and in the pre-push hook, on every machine,
// including one that has never installed node. A generator that lived in
// web/*.mjs would be the sixth gate nothing but a human ever runs, which is
// the property the four dark gates lacked and the reason they went dark.
//
// It writes the declarations from the structs' own json tags and diffs them
// against the committed web/wire.d.ts, failing with the same "run X and commit
// the result" message the editor-bundle staleness check already uses — so the
// fix is legible from the message alone.

// updateWire rewrites web/wire.d.ts instead of asserting it. `just wire`.
var updateWire = flag.Bool("update", false, "rewrite web/wire.d.ts from the Go structs")

// wireRoots is THE CONTRACT: every view struct the browser reads off
// /_galley/pending, /_galley/revise and /_galley/versions. Adding a struct here
// is how a new endpoint's payload becomes a type the browser cannot silently
// disagree with.
//
// The order is the order they are emitted in, and it is the order a reader
// meets them: the instruction round first, then the poll every page runs, then
// the history.
//
// TWO OF THESE WERE OUTSIDE IT UNTIL 2026-08-23, AND THE GAP HAD THE SAME SHAPE
// BOTH TIMES. GET /_galley/revise answered a `map[string]any` written inline —
// thirteen keys the page polls every second, none of them nameable in a .d.ts,
// so a rename could not have failed here and could only have failed in a
// browser as `undefined`. versionsView was a real struct whose CHILDREN
// (roundView, diffView, changeView) were all under contract while the envelope
// naming them was not, so `doc` and `rounds` were the two field names in the
// history payload nothing held either side to. A contract with a hole in the
// envelope is a contract about the letters and not the address.
var wireRoots = []any{
	PendingView{},
	InstructionView{},
	ReviseStateView{},
	versionsView{},
	roundView{},
	askView{},
	diffView{},
	changeView{},
}

const wirePath = "../../web/wire.d.ts"

func TestTheWireTypeIsCommitted(t *testing.T) {
	want := generateWire()
	if *updateWire {
		if err := os.WriteFile(filepath.Clean(wirePath), []byte(want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", wirePath)
		return
	}
	got, err := os.ReadFile(filepath.Clean(wirePath))
	if err != nil {
		t.Fatalf("the wire declarations are missing (%v) — run `just wire` and commit the result", err)
	}
	if string(got) != want {
		t.Errorf("the committed web/wire.d.ts does not match the Go structs — run `just wire` and commit the result\n\n%s",
			firstDifference(string(got), want))
	}
}

// firstDifference names the line that moved, because a whole-file diff of a
// generated declaration file is unreadable in a test log and the ONE thing the
// reader needs is which field changed.
func firstDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return fmt.Sprintf("first difference at line %d:\n  committed: %q\n  generated: %q", i+1, gl, wl)
		}
	}
	return "(files differ only in length)"
}

// generateWire renders the whole declaration file.
//
// HOW FAR A REFERENCE IS FOLLOWED, stated rather than discovered: as far as it
// goes. A field whose type is a struct — in THIS package or any other, named
// or pointed at or sliced — is emitted as its own interface and its own fields
// are walked in turn. `PendingView.Blocks` is `[]suggest.BlockRef` and
// `InstructionView.Region` is `*review.Region`, and both are types the browser
// genuinely reads, so a generator that stopped at the package boundary would
// emit `unknown` for exactly the fields a rename is most likely to break. The
// one terminal struct is `time.Time`, which is not a shape on the wire at all
// — it marshals to an RFC3339 string, so that is what it is declared as.
func generateWire() string {
	var b strings.Builder
	b.WriteString(wireHeader)

	seen := map[reflect.Type]bool{}
	var queue []reflect.Type
	for _, root := range wireRoots {
		rt := reflect.TypeOf(root)
		if !seen[rt] {
			seen[rt] = true
			queue = append(queue, rt)
		}
	}
	// Breadth-first from the roots, so the five contract structs come first
	// and anything they reach follows in the order it was reached. Nothing
	// here is sorted: a stable order that mirrors the Go source is what makes
	// the diff on a rename one line long.
	for i := 0; i < len(queue); i++ {
		t := queue[i]
		b.WriteString("\n")
		b.WriteString(renderInterface(t, func(dep reflect.Type) {
			if !seen[dep] {
				seen[dep] = true
				queue = append(queue, dep)
			}
		}))
	}
	return b.String()
}

func renderInterface(t reflect.Type, found func(reflect.Type)) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", tsName(t))
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue // unexported: encoding/json never writes it
		}
		name, opts := jsonName(f)
		if name == "-" {
			continue
		}
		typ := tsType(f.Type, found)
		optional := ""
		if opts.omitempty {
			// omitempty means the field is ABSENT from the payload when it is
			// the zero value, so the honest declaration is optional — and NOT
			// `| null`, because a nil slice under omitempty is omitted rather
			// than serialized as null.
			optional = "?"
		} else if nullable(f.Type) {
			// A slice, a map or a pointer with no omitempty reaches the
			// browser as JSON `null` when it is nil. Promising an array there
			// is how `for (const x of view.changes)` throws on a document that
			// simply had none — `PendingView.Changes` is the recorded case, and
			// `|| []` at its reader is load-bearing rather than defensive.
			typ += " | null"
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", name, optional, typ)
	}
	b.WriteString("}\n")
	return b.String()
}

func nullable(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Slice, reflect.Map, reflect.Pointer, reflect.Interface:
		return true
	}
	return false
}

var timeType = reflect.TypeOf(time.Time{})

func tsType(t reflect.Type, found func(reflect.Type)) string {
	if t == timeType {
		return "string"
	}
	switch t.Kind() {
	case reflect.Pointer:
		return tsType(t.Elem(), found)
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		return tsType(t.Elem(), found) + "[]"
	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key(), found), tsType(t.Elem(), found))
	case reflect.Struct:
		found(t)
		return tsName(t)
	default:
		// `unknown` and never `any`: a type the generator cannot name is a
		// type the browser must narrow before it uses, which is the rule the
		// spec sets for the whole conversion.
		return "unknown"
	}
}

// tsName is the Go type's own name with an exported first letter. The view
// structs are unexported on the Go side because nothing outside this package
// constructs one; the browser has no such notion, and `PendingView` as a
// TypeScript interface name would read as a variable.
func tsName(t reflect.Type) string {
	n := t.Name()
	if n == "" {
		return "unknown"
	}
	return strings.ToUpper(n[:1]) + n[1:]
}

type jsonOpts struct{ omitempty bool }

func jsonName(f reflect.StructField) (string, jsonOpts) {
	tag := f.Tag.Get("json")
	if tag == "" {
		return f.Name, jsonOpts{}
	}
	parts := strings.Split(tag, ",")
	name := parts[0]
	if name == "" {
		name = f.Name
	}
	var o jsonOpts
	for _, p := range parts[1:] {
		if p == "omitempty" {
			o.omitempty = true
		}
	}
	return name, o
}

// TestTheWireGeneratorFollowsACrossPackageReference is the check on the
// GENERATOR rather than on the contract, and it exists because "as far as it
// goes" is a claim about behaviour that the golden file cannot state on its
// own: a generator that emitted `unknown` for `[]suggest.BlockRef` and a
// wire.d.ts committed from it would agree with each other forever.
func TestTheWireGeneratorFollowsACrossPackageReference(t *testing.T) {
	out := generateWire()
	for _, want := range []string{
		"export interface BlockRef {",             // internal/suggest, reached through PendingView.Blocks
		"export interface Region {",               // internal/review, reached through InstructionView.Region
		"blocks?: BlockRef[];",                    // omitempty: absent, never null
		"instructions: InstructionView[] | null;", // no omitempty: nil reaches the browser as null
		"at: string;",                             // time.Time is terminal
	} {
		if !strings.Contains(out, want) {
			t.Errorf("generated wire.d.ts is missing %q", want)
		}
	}
	// Nothing may reach the browser as `any`, and nothing may silently become
	// `unknown` without somebody deciding it should.
	if strings.Contains(out, ": any") {
		t.Error("the generated wire carries `any`")
	}
	if n := strings.Count(out, "unknown"); n != 0 {
		lines := []string{}
		for _, l := range strings.Split(out, "\n") {
			if strings.Contains(l, "unknown") {
				lines = append(lines, strings.TrimSpace(l))
			}
		}
		sort.Strings(lines)
		t.Errorf("the generated wire carries %d unknown field(s): %v", n, lines)
	}
}

const wireHeader = `// wire.d.ts — THE GO↔JS CONTRACT, GENERATED. DO NOT EDIT.
//
// Written by internal/serve/wire_test.go from the json tags of the five view
// structs that ARE the wire: PendingView and InstructionView
// (internal/serve/editmode.go), roundView, diffView and changeView
// (internal/serve/versions.go), plus every struct they reach — including
// across a package boundary, which is how suggest.BlockRef and review.Region
// get here.
//
// Regenerate with ` + "`just wire`" + `. A drift between this file and the Go
// structs fails ` + "`just verify`" + `, which is Go-only and therefore runs on every
// machine, in CI and in the pre-push hook, whether or not node is installed.
// That is the whole point of it: the rename of ` + "`pending.suggestions`" + ` to
// ` + "`pending.instructions`" + ` broke two browser gates and went unnoticed for
// weeks, because the only things that could see it were scripts nobody ran.
//
// READING THE OPTIONALITY, because it is stated honestly rather than
// conveniently:
//
//   - ` + "`x?: T`" + ` — the Go field carries ` + "`omitempty`" + `, so the key is ABSENT from
//     the payload when it is the zero value. An absent slice is not an empty
//     one and is not null.
//   - ` + "`x: T[] | null`" + ` — no ` + "`omitempty`" + `, so a nil slice is serialized as JSON
//     ` + "`null`" + `. The type says so rather than promising an array: ` + "`|| []`" + ` at the
//     reader is load-bearing, and a declaration that hid this would make the
//     one line protecting against it look like superstition.
//   - a ` + "`time.Time`" + ` is a string. It is not a shape on the wire.
`
