#!/usr/bin/env python3
"""Fail when web/ gains a dead-code finding.

Reads `fallow dead-code --format json` on stdin and compares `total_issues`
against a ceiling. A ceiling and not zero, because the four standing findings
are not going to clear and should not be pretended away:

  3 x unused class member   VersionsPanel.show, VersionsPanel.hide and
                            SuggestionUI.restage — all called cross-file through
                            an instance fallow's class-member analysis does not
                            follow. A false positive, checked by grep at the
                            call sites. (It was `toggle` and `showRound` until
                            History was retired; the count did not move, because
                            the two that replaced them are called the same way.)
  1 x duplicate export      `BlockRef`, declared in trail.ts and in the
                            generated wire.d.ts. Two distinct types that share
                            a name; wire.d.ts is generated by a Go test and
                            editing it by hand does not survive `just wire`.

So a FIFTH finding is a red build, and nothing new arrives under cover of those
four. The branch that clears one lowers the number with it — and if fallow ever
learns to follow an instance method, this drops to 1 on its own.

AND TWO PACKAGES ARE IGNORED IN .fallowrc.json RATHER THAN COUNTED HERE.
`@fontsource/instrument-sans` and `@fontsource/jetbrains-mono` are the SOURCE of
the seven woff2 faces vendored into internal/serve/assets/fonts and of their
OFL licence; nothing imports them at build time and nothing should, since the
editor serves the files itself. They are a real dependency of the refresh, not
a finding, so they are declared as ignored where the tool can read it instead of
being paid for out of this bound.

A NOTE ON WHAT THIS TOOL MEANS BY "unused export": no external importer, NOT
unused symbol. A triage of 36 of these found 32 were symbols used perfectly
well inside their own file. Never delete on this tool's say-so; narrow the
export instead, which is what that sweep did.
"""
import json
import sys

BOUND = 4

data = json.load(sys.stdin)
n = data["total_issues"]
print(f"dead code: {n} findings — bound {BOUND}")
if n > BOUND:
    for key in ("unused_files", "unused_exports", "unused_types",
                "unused_class_members", "duplicate_exports"):
        for f in data.get(key) or []:
            print(f"  {key}: {f}")
    sys.exit(1)
